In [1]:
# !pip install --force-reinstall ibm_db==3.1.0 ibm_db_sa==0.3.3
# #Ensure we don't load_ext with sqlalchemy>=1.4 (incompadible)
# !pip uninstall sqlalchemy==1.4 -y && pip install sqlalchemy==1.3.24
# !pip install ipython-sql

In [2]:
import pandas as pd
import numpy as np
import ibm_db,ibm_db_sa
import ibm_db_dbi

# Connecting to IBM CloudPak DB2

In [3]:
%load_ext sql
# run custom file with IBM's CloudPak DB2 credentials - for privacy purposes
%run hide/IBM_Db2-credentials.py

In [20]:
%reload_ext sql
# run custom file with IBM's CloudPak DB2 credentials - for privacy purposes
%run hide/IBM_Db2-credentials.py

In [5]:
%sql ibm_db_sa://{dsn_uid}:{dsn_pwd}@{dsn_hostname}:{dsn_port}/{dsn_database}?security={dsn_security}

# Querying Data

In [7]:
%%sql 
select * from CENSUS_DATA;

 * ibm_db_sa://bvr08213:***@54a2f15b-5c0f-46df-8954-7e38e612c2bd.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32733/bludb
Done.

[(1, 'Rogers Park', 7.699999809265137, 23.600000381469727, 8.699999809265137, 18.200000762939453, 27.5, 23939, 39),
 (2, 'West Ridge', 7.800000190734863, 17.200000762939453, 8.800000190734863, 20.799999237060547, 38.5, 23040, 46),
 (3, 'Uptown', 3.799999952316284, 24.0, 8.899999618530273, 11.800000190734863, 22.200000762939453, 35787, 20),
 (4, 'Lincoln Square', 3.4000000953674316, 10.899999618530273, 8.199999809265137, 13.399999618530273, 25.5, 37524, 17),
 (5, 'North Center', 0.30000001192092896, 7.5, 5.199999809265137, 4.5, 26.200000762939453, 57123, 6),
 (6, 'Lake View', 1.100000023841858, 11.399999618530273, 4.699999809265137, 2.5999999046325684, 17.0, 60058, 5),
 (7, 'Lincoln Park', 0.800000011920929, 12.300000190734863, 5.099999904632568, 3.5999999046325684, 21.5, 71551, 2),
 (8, 'Near North Side', 1.899999976158142, 12.899999618530273, 7.0, 2.5, 22.600000381469727, 88669, 1),
 (9, 'Edison Park', 1.100000023841858, 3.299999952316284, 6.5, 7.400000095367432, 35.29999923706055, 40959, 8),
 (10, 'Norwood Park', 2.0, 5.400000095367432, 9.0, 11.5, 39.5, 32875, 21),
 (11, 'Jefferson Park', 2.700000047683716, 8.600000381469727, 12.399999618530273, 13.399999618530273, 35.5, 27751, 25),
 (12, 'Forest Glen', 1.100000023841858, 7.5, 6.800000190734863, 4.900000095367432, 40.5, 44164, 11),
 (13, 'North Park', 3.9000000953674316, 13.199999809265137, 9.899999618530273, 14.399999618530273, 39.0, 26576, 33),
 (14, 'Albany Park', 11.300000190734863, 19.200000762939453, 10.0, 32.900001525878906, 32.0, 21323, 53),
 (15, 'Portage Park', 4.099999904632568, 11.600000381469727, 12.600000381469727, 19.299999237060547, 34.0, 24336, 35),
 (16, 'Irving Park', 6.300000190734863, 13.100000381469727, 10.0, 22.399999618530273, 31.600000381469727, 27249, 34),
 (17, 'Dunning', 5.199999809265137, 10.600000381469727, 10.0, 16.200000762939453, 33.599998474121094, 26282, 28),
 (18, 'Montclaire', 8.100000381469727, 15.300000190734863, 13.800000190734863, 23.5, 38.599998474121094, 22014, 50),
 (19, 'Belmont Cragin', 10.800000190734863, 18.700000762939453, 14.600000381469727, 37.29999923706055, 37.29999923706055, 15461, 70),
 (20, 'Hermosa', 6.900000095367432, 20.5, 13.100000381469727, 41.599998474121094, 36.400001525878906, 15089, 71),
 (21, 'Avondale', 6.0, 15.300000190734863, 9.199999809265137, 24.700000762939453, 31.0, 20039, 42),
 (22, 'Logan Square', 3.200000047683716, 16.799999237060547, 8.199999809265137, 14.800000190734863, 26.200000762939453, 31908, 23),
 (23, 'Humboldt park', 14.800000190734863, 33.900001525878906, 17.299999237060547, 35.400001525878906, 38.0, 13781, 85),
 (24, 'West Town', 2.299999952316284, 14.699999809265137, 6.599999904632568, 12.899999618530273, 21.700000762939453, 43198, 10),
 (25, 'Austin', 6.300000190734863, 28.600000381469727, 22.600000381469727, 24.399999618530273, 37.900001525878906, 15957, 73),
 (26, 'West Garfield Park', 9.399999618530273, 41.70000076293945, 25.799999237060547, 24.5, 43.599998474121094, 10934, 92),
 (27, 'East Garfield Park', 8.199999809265137, 42.400001525878906, 19.600000381469727, 21.299999237060547, 43.20000076293945, 12961, 83),
 (28, 'Near West Side', 3.799999952316284, 20.600000381469727, 10.699999809265137, 9.600000381469727, 22.200000762939453, 44689, 15),
 (29, 'North Lawndale', 7.400000095367432, 43.099998474121094, 21.200000762939453, 27.600000381469727, 42.70000076293945, 12034, 87),
 (30, 'South Lawndale', 15.199999809265137, 30.700000762939453, 15.800000190734863, 54.79999923706055, 33.79999923706055, 10402, 96),
 (31, 'Lower West Side', 9.600000381469727, 25.799999237060547, 15.800000190734863, 40.70000076293945, 32.599998474121094, 16444, 76),
 (32, 'Loop', 1.5, 14.699999809265137, 5.699999809265137, 3.0999999046325684, 13.5, 65526, 3),
 (33, 'Near South Side', 1.2999999523162842, 13.800000190734863, 4.900000095367432, 7.400000095367432, 21.799999237060547, 59077, 7),
 (34, 'Armour Square', 5.699999809265137, 40.099998474121094, 16.700000762939453, 34.5, 38.29999923706055, 16148, 82),
 (35, 'Douglas', 1.7999999523162842, 29.600000381469727, 18.200000762939453, 14.300000190734863, 30.700000762939453, 23791, 47),
 (36, 'Oakland', 1.2999999523162842, 39.70000076293945, 28.700000762939453, 18.399999618530273, 40.400001525878906, 19252, 78),
 (37, 'Fuller Park', 3.200000047683716, 51.20000076293945, 33.900001525878906, 26.600000381469727, 44.900001525878906, 10432, 97),
 (38, 'Grand Boulevard', 3.299999952316284, 29.299999237060547, 24.299999237060547, 15.899999618530273, 39.5, 23472, 57),
 (39, 'Kenwood', 2.4000000953674316, 21.700000762939453, 15.699999809265137, 11.300000190734863, 35.400001525878906, 35911, 26),
 (40, 'Washington Park', 5.599999904632568, 42.099998474121094, 28.600000381469727, 25.399999618530273, 42.79999923706055, 13785, 88),
 (41, 'Hyde Park', 1.5, 18.399999618530273, 8.399999618530273, 4.300000190734863, 26.200000762939453, 39056, 14),
 (42, 'Woodlawn', 2.9000000953674316, 30.700000762939453, 23.399999618530273, 16.5, 36.099998474121094, 18672, 58),
 (43, 'South Shore', 2.799999952316284, 31.100000381469727, 20.0, 14.0, 35.70000076293945, 19398, 55),
 (44, 'Chatham', 3.299999952316284, 27.799999237060547, 24.0, 14.5, 40.29999923706055, 18881, 60),
 (45, 'Avalon Park', 1.399999976158142, 17.200000762939453, 21.100000381469727, 10.600000381469727, 39.29999923706055, 24454, 41),
 (46, 'South Chicago', 4.699999809265137, 29.799999237060547, 19.700000762939453, 26.600000381469727, 41.099998474121094, 16579, 75),
 (47, 'Burnside', 6.800000190734863, 33.0, 18.600000381469727, 19.299999237060547, 42.70000076293945, 12515, 79),
 (48, 'Calumet Heights', 2.0999999046325684, 11.5, 20.0, 11.0, 44.0, 28887, 38),
 (49, 'Roseland', 2.5, 19.799999237060547, 20.299999237060547, 16.899999618530273, 41.20000076293945, 17949, 52),
 (50, 'Pullman', 1.5, 21.600000381469727, 22.799999237060547, 13.100000381469727, 38.599998474121094, 20588, 51),
 (51, 'South Deering', 4.0, 29.200000762939453, 16.299999237060547, 21.0, 39.5, 14685, 65),
 (52, 'East Side', 6.800000190734863, 19.200000762939453, 12.100000381469727, 31.899999618530273, 42.79999923706055, 17104, 64),
 (53, 'West Pullman', 3.299999952316284, 25.899999618530273, 19.399999618530273, 20.5, 42.099998474121094, 16563, 62),
 (54, 'Riverdale', 5.800000190734863, 56.5, 34.599998474121094, 27.5, 51.5, 8201, 98),
 (55, 'Hegewisch', 3.299999952316284, 17.100000381469727, 9.600000381469727, 19.200000762939453, 42.900001525878906, 22677, 44),
 (56, 'Garfield Ridge', 2.5999999046325684, 8.800000190734863, 11.300000190734863, 19.299999237060547, 38.099998474121094, 26353, 32),
 (57, 'Archer Heights', 8.5, 14.100000381469727, 16.5, 35.900001525878906, 39.20000076293945, 16134, 67),
 (58, 'Brighton Park', 14.399999618530273, 23.600000381469727, 13.899999618530273, 45.099998474121094, 39.29999923706055, 13089, 84),
 (59, 'McKinley Park', 7.199999809265137, 18.700000762939453, 13.399999618530273, 32.900001525878906, 35.599998474121094, 16954, 61),
 (60, 'Bridgeport', 4.5, 18.899999618530273, 13.699999809265137, 22.200000762939453, 31.299999237060547, 22694, 43),
 (61, 'New City', 11.899999618530273, 29.0, 23.0, 41.5, 38.900001525878906, 12765, 91),
 (62, 'West Elsdon', 11.100000381469727, 15.600000381469727, 16.700000762939453, 37.0, 37.70000076293945, 15754, 69),
 (63, 'Gage Park', 15.800000190734863, 23.399999618530273, 18.200000762939453, 51.5, 38.79999923706055, 12171, 93),
 (64, 'Clearing', 2.700000047683716, 8.899999618530273, 9.5, 18.799999237060547, 37.599998474121094, 25113, 29),
 (65, 'West Lawn', 5.800000190734863, 14.899999618530273, 9.600000381469727, 33.599998474121094, 39.599998474121094, 16907, 56),
 (66, 'Chicago Lawn', 7.599999904632568, 27.899999618530273, 17.100000381469727, 31.200000762939453, 40.599998474121094, 13231, 80),
 (67, 'West Englewood', 4.800000190734863, 34.400001525878906, 35.900001525878906, 26.299999237060547, 40.70000076293945, 11317, 89),
 (68, 'Englewood', 3.799999952316284, 46.599998474121094, 28.0, 28.5, 42.5, 11888, 94),
 (69, 'Greater Grand Crossing', 3.5999999046325684, 29.600000381469727, 23.0, 16.5, 41.0, 17285, 66),
 (70, 'Ashburn', 4.0, 10.399999618530273, 11.699999809265137, 17.700000762939453, 36.900001525878906, 23482, 37),
 (71, 'Auburn Gresham', 4.0, 27.600000381469727, 28.299999237060547, 18.5, 41.900001525878906, 15528, 74),
 (72, 'Beverly', 0.8999999761581421, 5.099999904632568, 8.0, 3.700000047683716, 40.5, 39523, 12),
 (73, 'Washington Height', 1.100000023841858, 16.899999618530273, 20.799999237060547, 13.699999809265137, 42.599998474121094, 19713, 48),
 (74, 'Mount Greenwood', 1.0, 3.4000000953674316, 8.699999809265137, 4.300000190734863, 36.79999923706055, 34381, 16),
 (75, 'Morgan Park', 0.800000011920929, 13.199999809265137, 15.0, 10.800000190734863, 40.29999923706055, 27149, 30),
 (76, 'O Hare', 3.5999999046325684, 15.399999618530273, 7.099999904632568, 10.899999618530273, 30.299999237060547, 25828, 24),
 (77, 'Edgewater', 4.099999904632568, 18.200000762939453, 9.199999809265137, 9.699999809265137, 23.799999237060547, 33385, 19)]

In [24]:
census_data = pd.read_sql('select * from CENSUS_DATA',hdbi)
census_data

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1,Rogers Park,7.7,23.600000,8.700000,18.200001,27.500000,23939,39
1,2,West Ridge,7.8,17.200001,8.800000,20.799999,38.500000,23040,46
2,3,Uptown,3.8,24.000000,8.900000,11.800000,22.200001,35787,20
3,4,Lincoln Square,3.4,10.900000,8.200000,13.400000,25.500000,37524,17
4,5,North Center,0.3,7.500000,5.200000,4.500000,26.200001,57123,6
...,...,...,...,...,...,...,...,...,...
72,73,Washington Height,1.1,16.900000,20.799999,13.700000,42.599998,19713,48
73,74,Mount Greenwood,1.0,3.400000,8.700000,4.300000,36.799999,34381,16
74,75,Morgan Park,0.8,13.200000,15.000000,10.800000,40.299999,27149,30
75,76,O Hare,3.6,15.400000,7.100000,10.900000,30.299999,25828,24
76,77,Edgewater,4.1,18.200001,9.200000,9.700000,23.799999,33385,19

In [26]:
crime_data = pd.read_sql('select * from CRIME_DATA',hdbi)
crime_data

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807442,-87.703957,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898281,-87.716408,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624641,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743664,-87.562462,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773457,-87.706482,"(41.773455295, -87.706480471)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,10453948,HZ192829,2016-03-01,028XX E 79TH ST,1055,HUMAN TRAFFICKING,INVOLUNTARY SERVITUDE,APARTMENT,False,False,...,4,7.0,46.0,26,1196679.0,1853139.0,2016,41.751884,-87.554825,"(41.751885152, -87.554825997)"
529,10397129,HZ133234,2016-01-29,006XX W HARRISON ST,5114,NON - CRIMINAL,FOID - REVOCATION,STREET,False,False,...,1,2.0,28.0,26,1172257.0,1897564.0,2016,41.874363,-87.643013,"(41.874363279, -87.643013039)"
530,3269495,HJ747227,2003-11-08,012XX W 81ST ST,510,RITUALISM,AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY,OTHER,False,False,...,6,21.0,71.0,04B,1169648.0,1851076.0,2003,41.746853,-87.653938,"(41.746852486, -87.653941385)"
531,10840565,JA143710,2017-02-06,009XX N KARLOV AVE,5073,NON-CRIMINAL (SUBJECT SPECIFIED),NOTIFICATION OF CIVIL NO CONTACT ORDER,RESIDENCE,False,True,...,11,37.0,23.0,26,1148881.0,1905963.0,2017,41.897896,-87.728622,"(41.89789489, -87.728622316)"
532,1326195,G021609,2001-01-11,087XX S ESCANABA AV,9901,DOMESTIC VIOLENCE,DOMESTIC VIOLENCE,APARTMENT,True,True,...,4,NaN,NaN,08B,1196869.0,1847416.0,2001,41.736176,-87.554321,"(41.73617608, -87.554319607)"

In [23]:
school_data = pd.read_sql('select * from PUBLIC_SCHOOLS',hdbi)
school_data

,SCHOOL_ID,NAME_OF_SCHOOL,ELEMENTARY_MIDDLE_OR_HIGH_SCHOOL,STREET_ADDRESS,CITY,STATE,ZIP_CODE,PHONE_NUMBER,LINK,NETWORK_MANAGER,...,FRESHMAN_ON_TRACK_RATE__,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,WARD,POLICE_DISTRICT,LOCATION
0,400018,Austin Business and Entrepreneurship Academy H...,HS,231 N Pine Ave,Chicago,IL,60644,(773) 534-6316,None,West Side High School Network,...,NaN,1139494.763,1901274.2580000001,41.885204,-87.763214,25,AUSTIN,28,15,"(41.88520477, -87.76321191)"
1,609674,Chicago Vocational Career Academy High School,HS,2100 E 87th St,Chicago,IL,60617,(773) 535-6100,http://schoolreports.cps.edu/SchoolProgressRep...,South Side High School Network,...,44.099998,1191700.5929999999,1847743.551,41.737202,-87.573242,45,AVALON PARK,8,4,"(41.73720173, -87.57324389)"
2,609676,Paul Laurence Dunbar Career Academy High School,HS,3000 S King Dr,Chicago,IL,60616,(773) 534-9000,http://schoolreports.cps.edu/SchoolProgressRep...,South Side High School Network,...,65.699997,1179262.097,1885167.032,41.840187,-87.617676,35,DOUGLAS,2,1,"(41.84018775, -87.61767315)"
3,609678,William Jones College Preparatory High School,HS,606 S State St,Chicago,IL,60605,(773) 534-8600,http://schoolreports.cps.edu/SchoolProgressRep...,South Side High School Network,...,92.800003,1176412.354,1897618.0880000002,41.874420,-87.627754,32,LOOP,2,1,"(41.87441898, -87.62775497)"
4,609679,Charles Allen Prosser Career Academy High School,HS,2148 N Long Ave,Chicago,IL,60639,(773) 534-3200,http://schoolreports.cps.edu/SchoolProgressRep...,North-Northwest Side High School Network,...,79.400002,1139989.443,1913970.649,41.920036,-87.761086,19,BELMONT CRAGIN,37,25,"(41.92003613, -87.76108432)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NaN,1137482.2959999999,1919394.9,41.934967,-87.770164,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
562,610541,Federico Garcia Lorca Elementary School,ES,3231 N Springfield Ave,Chicago,IL,60618,(773) 534-0950,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NaN,1149828.0590000001,1921320.477,41.940018,-87.724747,21,AVONDALE,30,17,"(41.94001885, -87.72474354)"
563,610542,West Ridge Elementary School,ES,6700 N Whipple St,Chicago,IL,60645,(773) 534-8250,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,NaN,1154772.178,1944306.386,42.002995,-87.705956,2,WEST RIDGE,50,24,"(42.00299575, -87.70595357)"
564,610543,Eric Solorio Academy High School,HS,5400 S St Louis Ave,Chicago,IL,60632,(773) 535-9070,http://schoolreports.cps.edu/SchoolProgressRep...,AUSL Schools,...,85.599998,1153924.117,1868568.611,41.795181,-87.711098,63,GAGE PARK,14,8,"(41.79518118, -87.71109447)"
565,610544,Mariano Azuela Elementary School,ES,4707 W Marquette Rd,Chicago,IL,60629,(773) 535-7395,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NaN,1146123.64,1859720.388,41.771053,-87.739922,65,WEST LAWN,13,8,"(41.77105158, -87.73992325)"

In [29]:
print(dsn[:15])

DRIVER={IBM DB2

# Closing Connection

In [ ]:
# closing the connection (session)

connections = %sql -l
[c.session.close() for c in connections.values()]